apiVersion: v1
kind: ConfigMap
metadata:
  name: db-seed
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    {{- include "..dbLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "..dbSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "..dbSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: db
          image: postgres
          ports:
            - name: psql
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: db-seed
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_DB
              value: app
      volumes:
        - name: db-seed
          configMap:
            name: db-seed
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
  selector:
    {{- include "..dbSelectorLabels" . | nindent 4 }}